spring:
  application:
    name: forwarder
  datasource:
    url: ${PSQL_URL:jdbc:postgresql://localhost:5432/}
    username: postgres
    password:
    hikari:
      maximum-pool-size: 30

scheduling:
  enabled: ${SCHEDULING_ENABLED:true}

receiver:
  baseurl: ${RECEIVER_BASE_URL:http://localhost:8081}
  uripath: ${RECEIVER_URI_PATH:/event-receiver/event}